### ISSUE TITLE
Invalid records and impact on timers

### ISSUE THREAD

**Issue by hannestschofenig** [tlswg/dtls13-spec#224]
Zaheduzzaman Sarker wrote
 
> * Section 4.5.2: I assume the silent discard of invalid records will not impact the timers, is that a valid assumption? if yes, then it would be good if this is clarified in the text. 

-> need to add text

**Comment by ekr** [comment]
I don't actually understand the ask here. Why would it matter?

**Comment by hannestschofenig** [comment]
I believe he wants us to note that when an invalid record is received and silently discarded then it does not impact timers in any way. It would be surprising if it did but do we want to add a sentence about that?

**Comment by kaduk** [comment]
Since we have a dedicated section for "handling invalid records" that does allow for things other than silent discard, it makes sense to mention the lack of effect on timers.  "[...] however, an error MAY be logged for diagnostic purposes.  In no case does an invalid record affect pending retransmission timers."?

**Comment by ekr** [comment]
I'm not sure I agree, but I added something.
