### ISSUE TITLE
Old epochs

### ISSUE THREAD

**Issue by martinthomson** [tlswg/dtls13-spec#70]
> Until the handshake has completed, implementations MUST accept packets from the old epoch.

I think that this is a vestige of renegotiation and can be removed.  But we might want to say something more helpful about accepting 0-RTT and Handshake at the same time.

**Comment by hannestschofenig** [comment]
I think we should delete this sentence because it is redundant. We have already text in the same section saying the following:
"
Because DTLS records could be reordered, a record from epoch
1 may be received after epoch 2 has begun.  In general,
implementations SHOULD discard packets from earlier epochs, but if
packet loss causes noticeable problems implementations MAY choose to
retain keying material from previous epochs for up to the default MSL
specified for TCP to allow for packet reordering.
"

@Martin: If you think there is someone else that should be said, we are happy to add it. 

Here is the PR: 
https://github.com/tlswg/dtls13-spec/pull/95

**Comment by ekr** [comment]
Fixed.
