### ISSUE TITLE
What if ClientHello.cookie is not empty?

### ISSUE THREAD

**Issue by martinthomson** [tlswg/dtls13-spec#76]
Should the server reject the ClientHello if it appears as though the client is responding to a HelloVerifyRequest?  What if it also contains a cookie extension?

**Comment by hannestschofenig** [comment]
I don't think the server should reject a ClientHello if it thinks the Client should provide a cookie previously sent with the HelloVerifyRequest. This would require the server to keep state and to implement more complex logic in the server-side. 

If the ClientHello contains a cookie in the ClientHello.legacy_cookie field in the DTLS 1.3 field then IMHO an "illegal_parameter" alert has to be sent. I created a PR to add a note about this:
https://github.com/tlswg/dtls13-spec/pull/93

There is, however, the question why whether we should omit some of the legacy fields for use with DTLS 1.3 (not in the ClientHello because it would be needed for backwards compatibility) but for the ServerHello/HelloRetryRequest.

**Comment by ekr** [comment]
Fixed
